### PR TITLE
Added prune bans command

### PR DESCRIPTION
**Pull request by IvoDeK**
Needs to be debugged first before merge. Seems to have some issue with more than 1000 bans (more than 10 minutes)

### CODE REVIEW

**Comment by IvoDeK** [comment]
This is due to Discord timeouts. After 15 minutes Discord lets the slash command expire.

["Interaction tokens are valid for 15 minutes, meaning you can respond to an interaction within that amount of time."](https://discord.com/developers/docs/interactions/receiving-and-responding#followup-messages)

Solutions:

1. Easiest and probably cleanest fix is to not send a done message at all
2. Create a non ephemeral message separate from the command so you can always edit the message
3. Send a new message in channel non ephemeral telling user that process is done.

Also note caching doesn't work as is now.

**Comment by eekhohq** [comment]
Best in my opinion is by default 1, with an optional bool input added to the slash command for a done message (so option 3)

**Comment by IvoDeK** [comment]
Ready for review.

**Comment by IvoDeK** [comment]
Forgot to add bot permission should be fixed now.

**Review by eekhohq — APPROVED** [review]
Code looks good, can't find inconsistencies.

**Pull request merged**
